# SPDX-License-Identifier: MIT

description: Deadzone filter for sensor input

compatible: "zmk,sensor-filter-deadzone"

include: base.yaml

properties:
  threshold:
    type: int
    required: true
    description: |
      Deadzone threshold; values below this will be zeroed out.
